testing

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -1,4 +1,4 @@
-name: Run tests
+name: Run tests and deploy
 
 on:
   push:
@@ -20,7 +20,7 @@ jobs:
         run: npm install
 
       - name: Run tests
-        run: npm run test -- --coverage
+        run: npm test
 
   check-coverage:
     runs-on: ubuntu-latest
@@ -32,56 +32,45 @@ jobs:
 
       - name: Check test coverage
         run: |
-          if [ ! -f ./coverage/coverage-final.json ]; then
-            echo "Coverage report not found!"
-            exit 1
+          if [ ! -f ./coverage/coverage-summary.json ]; then
+          echo "Coverage report not found!"
+          exit 1
           fi
 
-          COVERAGE=$(jq '.[].s | select(. != null) | .[]' ./coverage/coverage-final.json)
+          echo "Coverage report found"
 
-          TOTAL=0
-          COUNT=0
+          COVERAGE=$(cat ./coverage/coverage-summary.json | jq .total.lines.pct)
+          echo "Test coverage is ${COVERAGE}%"
 
-          for value in $COVERAGE; do
-            TOTAL=$(echo "$TOTAL + $value" | bc)
-            COUNT=$((COUNT + 1))
-          done
-
-          if [ $COUNT -eq 0 ]; then
-            echo "No coverage data found!"
-            exit 1
+          if (( $(echo "$COVERAGE < 90" | bc -l) )); then
+          echo "Test coverage is below 90%, cannot deploy."
+          exit 1
           fi
 
-          AVERAGE=$(echo "scale=2; $TOTAL / $COUNT" | bc)
-          echo "Average lines coverage is ${AVERAGE}%"
-
-          if (( $(echo "$AVERAGE < 90" | bc -l) )); then
-            echo "Test coverage is below 90%, cannot deploy."
-            exit 1
-          fi
-
-          echo "Test coverage is sufficient."
   deploy:
     runs-on: ubuntu-latest
     needs: check-coverage
+    permissions:
+      contents: read
+      pages: write
+      id-token: write
 
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-
-      - name: Set up Node.js
-        uses: actions/setup-node@v3
-        with:
-          node-version: "20"
-
-      - name: Install dependencies
+      - uses: actions/checkout@v4
+      - name: Install modules
         run: npm install
 
-      - name: Build project
+      - name: Build dist
         run: npm run build
 
-      - name: Deploy to GitHub Pages
-        uses: peaceiris/actions-gh-pages@v3
+      - name: Setup pages
+        uses: actions/configure-pages@v3
+
+      - name: Upload dist folder
+        uses: actions/upload-pages-artifact@v1
         with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          publish_dir: ./dist
+          path: "./dist"
+
+      - name: Deploy to Github Pages
+        id: deployment
+        uses: actions/deploy-pages@v1
