pages aswell

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -33,16 +33,55 @@ jobs:
       - name: Check test coverage
         run: |
           if [ ! -f ./coverage/coverage-final.json ]; then
-          echo "Coverage report not found!"
-          exit 1
+            echo "Coverage report not found!"
+            exit 1
           fi
 
-          echo "Coverage report found"
+          COVERAGE=$(jq '.[].s | select(. != null) | .[]' ./coverage/coverage-final.json)
 
-          COVERAGE=$(cat ./coverage/coverage-final.json | jq .total.lines.pct)
-          echo "Test coverage is ${COVERAGE}%"
+          TOTAL=0
+          COUNT=0
 
-          if (( $(echo "$COVERAGE < 90" | bc -l) )); then
-          echo "Test coverage is below 90%, cannot deploy."
-          exit 1
+          for value in $COVERAGE; do
+            TOTAL=$(echo "$TOTAL + $value" | bc)
+            COUNT=$((COUNT + 1))
+          done
+
+          if [ $COUNT -eq 0 ]; then
+            echo "No coverage data found!"
+            exit 1
           fi
+
+          AVERAGE=$(echo "scale=2; $TOTAL / $COUNT" | bc)
+          echo "Average lines coverage is ${AVERAGE}%"
+
+          if (( $(echo "$AVERAGE < 90" | bc -l) )); then
+            echo "Test coverage is below 90%, cannot deploy."
+            exit 1
+          fi
+
+          echo "Test coverage is sufficient."
+  deploy:
+    runs-on: ubuntu-latest
+    needs: check-coverage
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Set up Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: "20"
+
+      - name: Install dependencies
+        run: npm install
+
+      - name: Build project
+        run: npm run build
+
+      - name: Deploy to GitHub Pages
+        uses: peaceiris/actions-gh-pages@v3
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          publish_dir: ./dist
